### ISSUE TITLE
File sentiment-words.txt

### ISSUE THREAD

**Issue by Ulitochka** [vineetjohn/linguistic-style-transfer#63]
Hello.
Where I can find the file: data/opinion-lexicon/sentiment-words.txt?

**Comment by vineetjohn** [comment]
@Ulitochka 

It is the Opinion Lexicon that can be downloaded from this website
https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html#lexicon

There are two separate files in the downloaded archive, just append them into a single file, which for the sentiment task, is 'sentiment-words.txt'.
Obviously, for other tasks, you would not use this file, and would return an empty set from [this function](https://github.com/vineetjohn/linguistic-style-transfer/blob/86ea24fc8ef860b573387db556af9ae165b44f32/linguistic_style_transfer_model/utils/lexicon_helper.py#L8).

**Comment by Ulitochka** [comment]
Thanks !
